/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.visao;

import br.com.projeto.controle.ClienteControle;
import br.com.projeto.negocio.entidades.Cliente;
import br.com.projeto.negocio.entidades.Endereco;
import br.com.projeto.negocio.entidades.Avaliacao;
import java.sql.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author julian
 */
public class jiCliente1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cliente
     */
    public jiCliente1() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtCPF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtEndereco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtComplemento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtEmail = new javax.swing.JTextField();
        jdData = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtRG = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtNumero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtBairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtCEP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcCidade = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtCelular = new javax.swing.JTextField();
        jtTelefone = new javax.swing.JTextField();
        jbCadastrar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        cbMillium = new java.awt.Checkbox();
        cbRugas = new java.awt.Checkbox();
        cbBolhas = new java.awt.Checkbox();
        cbDiscromia = new java.awt.Checkbox();
        cbComedao = new java.awt.Checkbox();
        cbNecrose = new java.awt.Checkbox();
        cbFisura = new java.awt.Checkbox();
        cbCouperose = new java.awt.Checkbox();
        cbTelangiectasia = new java.awt.Checkbox();
        cbEfelides = new java.awt.Checkbox();
        cbXantelasma = new java.awt.Checkbox();
        cbAtrofia = new java.awt.Checkbox();
        cbRosacea = new java.awt.Checkbox();
        cbHipocromia = new java.awt.Checkbox();
        cbPetequias = new java.awt.Checkbox();
        cbPustulas = new java.awt.Checkbox();
        cbUlceracao = new java.awt.Checkbox();
        cbHipertricose = new java.awt.Checkbox();
        cbSeborreia = new java.awt.Checkbox();
        cbCroasma = new java.awt.Checkbox();
        cbCianose = new java.awt.Checkbox();
        cbHematoma = new java.awt.Checkbox();
        cbVesicula = new java.awt.Checkbox();
        cbDescamacao = new java.awt.Checkbox();
        cbHirsutismo = new java.awt.Checkbox();
        cbHiperqueratose = new java.awt.Checkbox();
        cbFoliculite = new java.awt.Checkbox();
        cbAngioma = new java.awt.Checkbox();
        cbCeratose = new java.awt.Checkbox();
        cbNodulos = new java.awt.Checkbox();
        cbCrosta = new java.awt.Checkbox();
        cbEscoriacao = new java.awt.Checkbox();
        cbEczema = new java.awt.Checkbox();
        cbCicatriz = new java.awt.Checkbox();
        cbHipercromia = new java.awt.Checkbox();
        cbEritema = new java.awt.Checkbox();
        checkbox29 = new java.awt.Checkbox();
        checkbox30 = new java.awt.Checkbox();
        checkbox31 = new java.awt.Checkbox();
        checkbox32 = new java.awt.Checkbox();
        cbOleosidade = new java.awt.Checkbox();
        cbFlacidez = new java.awt.Checkbox();
        jButton1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cbEspessura1 = new java.awt.Checkbox();
        cbLesoes1 = new java.awt.Checkbox();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txBraco = new java.awt.TextField();
        tfBusto = new java.awt.TextField();
        tfQuladril = new java.awt.TextField();
        tfPerna = new java.awt.TextField();
        tfEstomago = new java.awt.TextField();
        tfCintura = new java.awt.TextField();
        tfAbdomem = new java.awt.TextField();
        tfCulote = new java.awt.TextField();
        tfCoxaBX = new java.awt.TextField();
        tfCoxaAt = new java.awt.TextField();
        jComboBox11 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jrbCelulite = new javax.swing.JRadioButton();
        jrbGorduraLoc = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jrbPtose = new javax.swing.JRadioButton();
        jrbVibices = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tfLocalGord = new java.awt.TextField();
        tfLocalPtose = new java.awt.TextField();
        tfLocalVibices = new java.awt.TextField();
        JbAvancarBiom = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cbCardiaca = new java.awt.Checkbox();
        cbProteses = new java.awt.Checkbox();
        cbMarcapasso = new java.awt.Checkbox();
        cbVasculares = new java.awt.Checkbox();
        cbBronquite = new java.awt.Checkbox();
        cbEplepsia = new java.awt.Checkbox();
        cbReumaticas = new java.awt.Checkbox();
        cbAlergicas = new java.awt.Checkbox();
        cbOncologia = new java.awt.Checkbox();
        cbRenais = new java.awt.Checkbox();
        cbDIU = new java.awt.Checkbox();
        cbGinecologicas = new java.awt.Checkbox();
        cbGlandulares = new java.awt.Checkbox();
        cbGestante = new java.awt.Checkbox();
        jLabel29 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        jPanel1.setLayout(null);

        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 40, 14);

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });
        jtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(jtNome);
        jtNome.setBounds(20, 30, 320, 30);

        jLabel2.setText("CPF:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(400, 190, 40, 14);

        jtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCPFFocusLost(evt);
            }
        });
        jtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCPFActionPerformed(evt);
            }
        });
        jPanel1.add(jtCPF);
        jtCPF.setBounds(400, 210, 230, 30);

        jLabel3.setText("Endereço:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 70, 14);

        jtEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtEnderecoFocusLost(evt);
            }
        });
        jtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEnderecoActionPerformed(evt);
            }
        });
        jPanel1.add(jtEndereco);
        jtEndereco.setBounds(20, 90, 320, 30);

        jLabel4.setText("Complemento:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 190, 90, 14);

        jtComplemento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtComplementoFocusLost(evt);
            }
        });
        jPanel1.add(jtComplemento);
        jtComplemento.setBounds(20, 210, 320, 30);

        jLabel5.setText("Cidade:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 300, 50, 14);

        jLabel6.setText("Email:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 360, 40, 14);

        jtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtEmailFocusLost(evt);
            }
        });
        jtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(jtEmail);
        jtEmail.setBounds(20, 390, 320, 30);

        jdData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdDataFocusLost(evt);
            }
        });
        jPanel1.add(jdData);
        jdData.setBounds(400, 30, 160, 30);

        jLabel14.setText("Data Nascimento: ");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(400, 10, 112, 20);

        jLabel7.setText("RG:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(400, 250, 30, 14);

        jtRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtRGFocusLost(evt);
            }
        });
        jPanel1.add(jtRG);
        jtRG.setBounds(400, 270, 230, 30);

        jLabel8.setText("Numero:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(400, 70, 50, 14);

        jtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNumeroFocusLost(evt);
            }
        });
        jtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(jtNumero);
        jtNumero.setBounds(400, 90, 140, 30);

        jLabel13.setText("Bairro:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 130, 40, 14);

        jtBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtBairroFocusLost(evt);
            }
        });
        jtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBairroActionPerformed(evt);
            }
        });
        jPanel1.add(jtBairro);
        jtBairro.setBounds(20, 150, 320, 30);

        jLabel9.setText("CEP:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(400, 130, 30, 14);

        jtCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCEPFocusLost(evt);
            }
        });
        jPanel1.add(jtCEP);
        jtCEP.setBounds(400, 150, 230, 30);

        jLabel10.setText("Estado:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 250, 50, 20);

        jcCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        jPanel1.add(jcCidade);
        jcCidade.setBounds(20, 270, 46, 20);

        jLabel11.setText("Telefone:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(400, 310, 60, 14);

        jLabel12.setText("Celular:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(400, 370, 50, 14);

        jtCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCelularFocusLost(evt);
            }
        });
        jPanel1.add(jtCelular);
        jtCelular.setBounds(400, 390, 230, 30);

        jtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtTelefoneFocusLost(evt);
            }
        });
        jtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(jtTelefone);
        jtTelefone.setBounds(400, 330, 230, 30);

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCadastrar);
        jbCadastrar.setBounds(400, 440, 110, 23);

        jbCancelar.setText("Cancelar");
        jPanel1.add(jbCancelar);
        jbCancelar.setBounds(570, 440, 110, 23);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3" }));
        jComboBox2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox2PropertyChange(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(20, 320, 124, 20);

        jTabbedPane1.addTab("Cadastro ", jPanel1);

        jPanel2.setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Branca", "Negra", "Amarela" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(100, 20, 70, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Boa", "Ruim" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(300, 20, 110, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Boa", "Ruim" }));
        jPanel2.add(jComboBox4);
        jComboBox4.setBounds(540, 20, 90, 20);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Boa", "Ruim" }));
        jPanel2.add(jComboBox6);
        jComboBox6.setBounds(300, 60, 110, 20);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Boa", "Ruim" }));
        jPanel2.add(jComboBox7);
        jComboBox7.setBounds(540, 60, 90, 20);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Boa", "Ruim" }));
        jPanel2.add(jComboBox9);
        jComboBox9.setBounds(100, 60, 70, 20);

        cbMillium.setLabel("Milium");
        cbMillium.setName("Millium"); // NOI18N
        jPanel2.add(cbMillium);
        cbMillium.setBounds(30, 170, 84, 20);

        cbRugas.setLabel("Rugas");
        jPanel2.add(cbRugas);
        cbRugas.setBounds(30, 200, 63, 20);

        cbBolhas.setLabel("Bolhas");
        jPanel2.add(cbBolhas);
        cbBolhas.setBounds(30, 230, 65, 20);

        cbDiscromia.setLabel("Discromia");
        jPanel2.add(cbDiscromia);
        cbDiscromia.setBounds(30, 260, 83, 20);

        cbComedao.setLabel("Comedão");
        jPanel2.add(cbComedao);
        cbComedao.setBounds(30, 290, 81, 20);

        cbNecrose.setLabel("Necrose");
        jPanel2.add(cbNecrose);
        cbNecrose.setBounds(30, 320, 73, 20);

        cbFisura.setLabel("Fisura");
        jPanel2.add(cbFisura);
        cbFisura.setBounds(30, 350, 61, 20);

        cbCouperose.setLabel("Couperose");
        jPanel2.add(cbCouperose);
        cbCouperose.setBounds(140, 170, 88, 20);

        cbTelangiectasia.setLabel("Telangiectasia");
        jPanel2.add(cbTelangiectasia);
        cbTelangiectasia.setBounds(270, 170, 100, 20);

        cbEfelides.setLabel("Efelides");
        jPanel2.add(cbEfelides);
        cbEfelides.setBounds(410, 170, 71, 20);

        cbXantelasma.setLabel("Xantelasma");
        jPanel2.add(cbXantelasma);
        cbXantelasma.setBounds(520, 170, 84, 20);

        cbAtrofia.setLabel("Atrofia");
        jPanel2.add(cbAtrofia);
        cbAtrofia.setBounds(30, 380, 84, 20);

        cbRosacea.setLabel("Rosacea");
        jPanel2.add(cbRosacea);
        cbRosacea.setBounds(140, 200, 76, 20);

        cbHipocromia.setLabel("Hipocromia");
        jPanel2.add(cbHipocromia);
        cbHipocromia.setBounds(140, 230, 90, 20);

        cbPetequias.setLabel("Petequias");
        jPanel2.add(cbPetequias);
        cbPetequias.setBounds(140, 260, 82, 20);

        cbPustulas.setLabel("Pustulas");
        jPanel2.add(cbPustulas);
        cbPustulas.setBounds(140, 290, 75, 20);

        cbUlceracao.setLabel("Ulceração");
        jPanel2.add(cbUlceracao);
        cbUlceracao.setBounds(140, 320, 82, 20);

        cbHipertricose.setLabel("Hipertricose");
        jPanel2.add(cbHipertricose);
        cbHipertricose.setBounds(140, 350, 93, 20);

        cbSeborreia.setLabel("Seborreia");
        jPanel2.add(cbSeborreia);
        cbSeborreia.setBounds(270, 200, 80, 20);

        cbCroasma.setLabel("Croasma");
        jPanel2.add(cbCroasma);
        cbCroasma.setBounds(270, 230, 78, 20);

        cbCianose.setLabel("Cianose");
        jPanel2.add(cbCianose);
        cbCianose.setBounds(270, 260, 73, 20);

        cbHematoma.setLabel("Hematoma");
        jPanel2.add(cbHematoma);
        cbHematoma.setBounds(270, 290, 88, 20);

        cbVesicula.setLabel("Vesicula");
        jPanel2.add(cbVesicula);
        cbVesicula.setBounds(270, 320, 73, 20);

        cbDescamacao.setLabel("Descamação");
        jPanel2.add(cbDescamacao);
        cbDescamacao.setBounds(270, 350, 100, 20);

        cbHirsutismo.setLabel("Hirsutismo");
        jPanel2.add(cbHirsutismo);
        cbHirsutismo.setBounds(270, 380, 87, 20);

        cbHiperqueratose.setLabel("Hiperqueratose");
        jPanel2.add(cbHiperqueratose);
        cbHiperqueratose.setBounds(140, 380, 110, 20);

        cbFoliculite.setLabel("Foliculite");
        jPanel2.add(cbFoliculite);
        cbFoliculite.setBounds(410, 200, 75, 20);

        cbAngioma.setLabel("Angioma");
        jPanel2.add(cbAngioma);
        cbAngioma.setBounds(410, 230, 75, 20);

        cbCeratose.setLabel("Ceratose");
        jPanel2.add(cbCeratose);
        cbCeratose.setBounds(410, 260, 77, 20);

        cbNodulos.setLabel("Nodulos");
        jPanel2.add(cbNodulos);
        cbNodulos.setBounds(410, 290, 73, 20);

        cbCrosta.setLabel("Crosta");
        jPanel2.add(cbCrosta);
        cbCrosta.setBounds(410, 320, 63, 20);

        cbEscoriacao.setLabel("Escoriação");
        jPanel2.add(cbEscoriacao);
        cbEscoriacao.setBounds(410, 350, 88, 20);

        cbEczema.setLabel("Eczema");
        jPanel2.add(cbEczema);
        cbEczema.setBounds(410, 380, 70, 20);

        cbCicatriz.setLabel("Cicatriz");
        jPanel2.add(cbCicatriz);
        cbCicatriz.setBounds(520, 200, 66, 20);

        cbHipercromia.setLabel("Hipercromia");
        jPanel2.add(cbHipercromia);
        cbHipercromia.setBounds(520, 230, 94, 20);

        cbEritema.setLabel("Eritema");
        jPanel2.add(cbEritema);
        cbEritema.setBounds(520, 260, 69, 20);

        checkbox29.setLabel("Papulas");
        jPanel2.add(checkbox29);
        checkbox29.setBounds(520, 290, 72, 20);

        checkbox30.setLabel("Escara");
        jPanel2.add(checkbox30);
        checkbox30.setBounds(520, 320, 65, 20);

        checkbox31.setLabel("Fistula");
        jPanel2.add(checkbox31);
        checkbox31.setBounds(520, 350, 63, 20);

        checkbox32.setLabel("Psoriase");
        jPanel2.add(checkbox32);
        checkbox32.setBounds(520, 140, 76, 20);

        cbOleosidade.setLabel("Oleosidade");
        cbOleosidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbOleosidadeFocusLost(evt);
            }
        });
        jPanel2.add(cbOleosidade);
        cbOleosidade.setBounds(30, 140, 90, 20);

        cbFlacidez.setLabel("Flacidez");
        jPanel2.add(cbFlacidez);
        cbFlacidez.setBounds(410, 140, 87, 20);

        jButton1.setText("Avançar");
        jPanel2.add(jButton1);
        jButton1.setBounds(570, 420, 73, 23);

        jLabel30.setText("Cor da Pele:");
        jPanel2.add(jLabel30);
        jLabel30.setBounds(30, 20, 70, 14);

        jLabel33.setText("Aparencia Pele:");
        jPanel2.add(jLabel33);
        jLabel33.setBounds(220, 20, 80, 14);

        jLabel34.setText("Biotipo Cultaneo:");
        jPanel2.add(jLabel34);
        jLabel34.setBounds(210, 60, 90, 14);

        jLabel35.setText("Desidratação:");
        jPanel2.add(jLabel35);
        jLabel35.setBounds(20, 60, 90, 14);

        jLabel36.setText("Superficies da Pele:");
        jPanel2.add(jLabel36);
        jLabel36.setBounds(430, 20, 94, 14);

        jLabel37.setText("Pele com Acne:");
        jPanel2.add(jLabel37);
        jLabel37.setBounds(450, 60, 90, 14);

        cbEspessura1.setLabel("Espessura");
        jPanel2.add(cbEspessura1);
        cbEspessura1.setBounds(140, 140, 87, 20);

        cbLesoes1.setLabel("Lesões");
        jPanel2.add(cbLesoes1);
        cbLesoes1.setBounds(270, 140, 87, 20);

        jTabbedPane1.addTab("Avaliação", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Braço:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel16.setText("Busto:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel17.setText("Quadril:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel18.setText("Perna:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel19.setText("Estomago:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel20.setText("Cintura:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel21.setText("Abdomem:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel22.setText("Culote:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        jLabel23.setText("Coxa BX:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        jLabel24.setText("Coxa At:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        txBraco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBracoActionPerformed(evt);
            }
        });
        jPanel3.add(txBraco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 90, -1));
        jPanel3.add(tfBusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 90, -1));
        jPanel3.add(tfQuladril, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 90, -1));
        jPanel3.add(tfPerna, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 90, -1));
        jPanel3.add(tfEstomago, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 100, -1));

        tfCintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCinturaActionPerformed(evt);
            }
        });
        jPanel3.add(tfCintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 100, -1));
        jPanel3.add(tfAbdomem, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 100, -1));
        jPanel3.add(tfCulote, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 100, -1));
        jPanel3.add(tfCoxaBX, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 100, -1));
        jPanel3.add(tfCoxaAt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 100, -1));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel3.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jLabel25.setText("Grau:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        jrbCelulite.setText("Celulite:");
        jPanel3.add(jrbCelulite, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jrbGorduraLoc.setText("Gordura Localizada");
        jPanel3.add(jrbGorduraLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel26.setText("Local:");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        jrbPtose.setText("Ptose");
        jPanel3.add(jrbPtose, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jrbVibices.setText("Vibices");
        jPanel3.add(jrbVibices, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel27.setText("Local:");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jLabel28.setText("Local:");
        jLabel28.setToolTipText("");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        tfLocalGord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLocalGordActionPerformed(evt);
            }
        });
        jPanel3.add(tfLocalGord, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 130, -1));
        jPanel3.add(tfLocalPtose, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 130, -1));
        jPanel3.add(tfLocalVibices, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 130, -1));

        JbAvancarBiom.setText("Avançar");
        jPanel3.add(JbAvancarBiom, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, -1, -1));

        jTabbedPane1.addTab("Biometria", jPanel3);

        cbCardiaca.setLabel("Cardiaca");

        cbProteses.setLabel("Proteses");

        cbMarcapasso.setLabel("Marcapasso");

        cbVasculares.setLabel("Vasculares");

        cbBronquite.setLabel("Bronquite");

        cbEplepsia.setLabel("Eplepsia");

        cbReumaticas.setLabel("Reumaticas");

        cbAlergicas.setLabel("Alergicas");

        cbOncologia.setLabel("Oncologia");

        cbRenais.setLabel("Renais");

        cbDIU.setLabel("DIU");

        cbGinecologicas.setLabel("Ginecologicas");

        cbGlandulares.setLabel("Glandulares");

        cbGestante.setLabel("Gestante");

        jLabel29.setText("Observações");

        jTextField1.setText(" ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton3.setText("Salvar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbCardiaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbProteses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbMarcapasso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbBronquite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbVasculares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbEplepsia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbReumaticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAlergicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbOncologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbGinecologicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbRenais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbDIU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbGestante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbGlandulares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCardiaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRenais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbReumaticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbVasculares, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbGlandulares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbBronquite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbProteses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbAlergicas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbGestante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(cbDIU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbMarcapasso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEplepsia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOncologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGinecologicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(8, 8, 8))
        );

        jTabbedPane1.addTab("Alteração", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeActionPerformed

    private void jtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCPFActionPerformed

    private void jtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEnderecoActionPerformed

    }//GEN-LAST:event_jtEnderecoActionPerformed

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        this.cliente.setNome(jtNome.getText());
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCPFFocusLost
        this.cliente.setCpf(jtCPF.getText());
    }//GEN-LAST:event_jtCPFFocusLost

    private void jtEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtEnderecoFocusLost
        this.endereco.setRua(jtEndereco.getText());
    }//GEN-LAST:event_jtEnderecoFocusLost

    private void jtComplementoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtComplementoFocusLost
        this.endereco.setComplemento(jtComplemento.getText());
    }//GEN-LAST:event_jtComplementoFocusLost

    private void jtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtEmailFocusLost
        this.cliente.setEmail(jtEmail.getText());
    }//GEN-LAST:event_jtEmailFocusLost

    private void jdDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdDataFocusLost
        DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date data = new java.sql.Date(fmt.parse(jdData.getDateFormatString()).getTime());
            this.cliente.setDataNascimento(data);
        } catch (ParseException ex) {
            Logger.getLogger(jiCliente1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jdDataFocusLost

    private void jtRGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtRGFocusLost
        this.cliente.setRg(jtRG.getText());
    }//GEN-LAST:event_jtRGFocusLost

    private void jtNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNumeroFocusLost
        this.endereco.setNumero(Integer.parseInt(jtNumero.getText()));
    }//GEN-LAST:event_jtNumeroFocusLost

    private void jtBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtBairroFocusLost
        this.endereco.setBairro(jtBairro.getText());
    }//GEN-LAST:event_jtBairroFocusLost

    private void jtCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCEPFocusLost
        this.endereco.setCEP(jtCEP.getText());
    }//GEN-LAST:event_jtCEPFocusLost

    private void jtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtTelefoneFocusLost
        this.cliente.setTelefone(jtTelefone.getText());
    }//GEN-LAST:event_jtTelefoneFocusLost

    private void jtCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCelularFocusLost
        this.cliente.setCelular(jtCelular.getText());
    }//GEN-LAST:event_jtCelularFocusLost

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        this.cliente.setEndereco(this.endereco);
        if (this.cliente.valida()) {
            clienteControle.adicionar(this.cliente);
            limparCampos();
        } else {
            StringBuilder mens = new StringBuilder();
            for (String mensagem : this.cliente.obterMensagens()) {
                mens.append(mensagem);
                mens.append("\n");
            }
            JOptionPane.showMessageDialog(null, mens);
            this.cliente.limparMensagens();
        }
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jComboBox2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox2PropertyChange
        this.endereco.setFk_idCidade(3);
    }//GEN-LAST:event_jComboBox2PropertyChange

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void txBracoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBracoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txBracoActionPerformed

    private void tfCinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCinturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCinturaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBairroActionPerformed

    private void jtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTelefoneActionPerformed

    private void jtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmailActionPerformed

    private void jtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNumeroActionPerformed

    private void tfLocalGordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLocalGordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLocalGordActionPerformed

    private void cbOleosidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbOleosidadeFocusLost
        if (cbOleosidade.getState()) {
            this.avaliacao.setOleosidadePele(1);
        } else {
            this.avaliacao.setOleosidadePele(0);
        }


    }//GEN-LAST:event_cbOleosidadeFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbAvancarBiom;
    private java.awt.Checkbox cbAlergicas;
    private java.awt.Checkbox cbAngioma;
    private java.awt.Checkbox cbAtrofia;
    private java.awt.Checkbox cbBolhas;
    private java.awt.Checkbox cbBronquite;
    private java.awt.Checkbox cbCardiaca;
    private java.awt.Checkbox cbCeratose;
    private java.awt.Checkbox cbCianose;
    private java.awt.Checkbox cbCicatriz;
    private java.awt.Checkbox cbComedao;
    private java.awt.Checkbox cbCouperose;
    private java.awt.Checkbox cbCroasma;
    private java.awt.Checkbox cbCrosta;
    private java.awt.Checkbox cbDIU;
    private java.awt.Checkbox cbDescamacao;
    private java.awt.Checkbox cbDiscromia;
    private java.awt.Checkbox cbEczema;
    private java.awt.Checkbox cbEfelides;
    private java.awt.Checkbox cbEplepsia;
    private java.awt.Checkbox cbEritema;
    private java.awt.Checkbox cbEscoriacao;
    private java.awt.Checkbox cbEspessura1;
    private java.awt.Checkbox cbFisura;
    private java.awt.Checkbox cbFlacidez;
    private java.awt.Checkbox cbFoliculite;
    private java.awt.Checkbox cbGestante;
    private java.awt.Checkbox cbGinecologicas;
    private java.awt.Checkbox cbGlandulares;
    private java.awt.Checkbox cbHematoma;
    private java.awt.Checkbox cbHipercromia;
    private java.awt.Checkbox cbHiperqueratose;
    private java.awt.Checkbox cbHipertricose;
    private java.awt.Checkbox cbHipocromia;
    private java.awt.Checkbox cbHirsutismo;
    private java.awt.Checkbox cbLesoes1;
    private java.awt.Checkbox cbMarcapasso;
    private java.awt.Checkbox cbMillium;
    private java.awt.Checkbox cbNecrose;
    private java.awt.Checkbox cbNodulos;
    private java.awt.Checkbox cbOleosidade;
    private java.awt.Checkbox cbOncologia;
    private java.awt.Checkbox cbPetequias;
    private java.awt.Checkbox cbProteses;
    private java.awt.Checkbox cbPustulas;
    private java.awt.Checkbox cbRenais;
    private java.awt.Checkbox cbReumaticas;
    private java.awt.Checkbox cbRosacea;
    private java.awt.Checkbox cbRugas;
    private java.awt.Checkbox cbSeborreia;
    private java.awt.Checkbox cbTelangiectasia;
    private java.awt.Checkbox cbUlceracao;
    private java.awt.Checkbox cbVasculares;
    private java.awt.Checkbox cbVesicula;
    private java.awt.Checkbox cbXantelasma;
    private java.awt.Checkbox checkbox29;
    private java.awt.Checkbox checkbox30;
    private java.awt.Checkbox checkbox31;
    private java.awt.Checkbox checkbox32;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox<String> jcCidade;
    private com.toedter.calendar.JDateChooser jdData;
    private javax.swing.JRadioButton jrbCelulite;
    private javax.swing.JRadioButton jrbGorduraLoc;
    private javax.swing.JRadioButton jrbPtose;
    private javax.swing.JRadioButton jrbVibices;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JTextField jtCEP;
    private javax.swing.JTextField jtCPF;
    private javax.swing.JTextField jtCelular;
    private javax.swing.JTextField jtComplemento;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtEndereco;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNumero;
    private javax.swing.JTextField jtRG;
    private javax.swing.JTextField jtTelefone;
    private java.awt.TextField tfAbdomem;
    private java.awt.TextField tfBusto;
    private java.awt.TextField tfCintura;
    private java.awt.TextField tfCoxaAt;
    private java.awt.TextField tfCoxaBX;
    private java.awt.TextField tfCulote;
    private java.awt.TextField tfEstomago;
    private java.awt.TextField tfLocalGord;
    private java.awt.TextField tfLocalPtose;
    private java.awt.TextField tfLocalVibices;
    private java.awt.TextField tfPerna;
    private java.awt.TextField tfQuladril;
    private java.awt.TextField txBraco;
    // End of variables declaration//GEN-END:variables

    private Cliente cliente = new Cliente();
    private Endereco endereco = new Endereco();
    private Avaliacao avaliacao = new Avaliacao();

    private ClienteControle clienteControle = new ClienteControle();

    private void limparCampos() {

    }

    private Vector estados = new Vector();

    public Vector getEstados() {
        return estados;
    }

}
