/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author ki_ob
 */
public class jifAvaliacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifAvaliacao
     */
    public jifAvaliacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jColorChooser1 = new javax.swing.JColorChooser();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jDialog3 = new javax.swing.JDialog();
        jCheckBox8 = new javax.swing.JCheckBox();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jCheckBox40 = new javax.swing.JCheckBox();
        jCheckBox41 = new javax.swing.JCheckBox();
        jCheckBox42 = new javax.swing.JCheckBox();
        jCheckBox43 = new javax.swing.JCheckBox();
        jCheckBox44 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jCheckBox8.setText("Fisura");

        setTitle("Avaliação");
        getContentPane().setLayout(null);
        getContentPane().add(filler1);
        filler1.setBounds(219, 306, 0, 0);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cor da Pele" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(10, 20, 107, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aparência da Pele" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(140, 20, 111, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Superfície da Pele" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(280, 20, 110, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lesões" }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(10, 60, 107, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biotipo Cultâneo" }));
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(140, 60, 111, 20);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pele com Acne" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(280, 60, 110, 20);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flacidez" }));
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(10, 100, 107, 20);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desidratação" }));
        getContentPane().add(jComboBox8);
        jComboBox8.setBounds(140, 100, 111, 20);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 133, 378, 10);

        jCheckBox1.setText("Couperose");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(105, 145, 77, 23);

        jCheckBox2.setText("Rugas");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(0, 168, 55, 23);

        jCheckBox3.setText("Bolhas");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(0, 191, 57, 23);

        jCheckBox4.setText("Discromia");
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(0, 214, 71, 23);

        jCheckBox5.setText("Comedão");
        getContentPane().add(jCheckBox5);
        jCheckBox5.setBounds(0, 237, 71, 23);

        jCheckBox6.setText("Necrose");
        getContentPane().add(jCheckBox6);
        jCheckBox6.setBounds(0, 260, 65, 23);

        jCheckBox7.setText("Fisura");
        getContentPane().add(jCheckBox7);
        jCheckBox7.setBounds(0, 283, 55, 23);

        jCheckBox9.setText("Atrofia");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox9);
        jCheckBox9.setBounds(0, 306, 59, 23);

        jCheckBox10.setText("Verrugas/ Pintas");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox10);
        jCheckBox10.setBounds(0, 329, 105, 23);

        jCheckBox11.setText("Seborreia");
        getContentPane().add(jCheckBox11);
        jCheckBox11.setBounds(105, 329, 71, 23);

        jCheckBox12.setText("Telangiectasia");
        getContentPane().add(jCheckBox12);
        jCheckBox12.setBounds(105, 306, 93, 23);

        jCheckBox13.setText("Ulceração");
        getContentPane().add(jCheckBox13);
        jCheckBox13.setBounds(105, 260, 73, 23);

        jCheckBox14.setText("Hipertricose");
        getContentPane().add(jCheckBox14);
        jCheckBox14.setBounds(105, 283, 83, 23);

        jCheckBox15.setText("Pustula");
        getContentPane().add(jCheckBox15);
        jCheckBox15.setBounds(105, 214, 61, 23);

        jCheckBox16.setText("Petequias");
        getContentPane().add(jCheckBox16);
        jCheckBox16.setBounds(105, 237, 73, 23);

        jCheckBox17.setText("Milinium");
        getContentPane().add(jCheckBox17);
        jCheckBox17.setBounds(0, 145, 61, 23);

        jCheckBox18.setText("Rosacea");
        getContentPane().add(jCheckBox18);
        jCheckBox18.setBounds(105, 168, 67, 23);

        jCheckBox19.setText("Hipocromia");
        getContentPane().add(jCheckBox19);
        jCheckBox19.setBounds(105, 191, 77, 23);

        jCheckBox20.setText("Efelides");
        getContentPane().add(jCheckBox20);
        jCheckBox20.setBounds(299, 283, 63, 23);

        jCheckBox21.setText("Croasma");
        getContentPane().add(jCheckBox21);
        jCheckBox21.setBounds(200, 145, 67, 23);

        jCheckBox22.setText("Hiperqueratose");
        getContentPane().add(jCheckBox22);
        jCheckBox22.setBounds(200, 306, 99, 23);

        jCheckBox23.setText("Cianose");
        getContentPane().add(jCheckBox23);
        jCheckBox23.setBounds(200, 168, 63, 23);

        jCheckBox24.setText("Hirsutismo");
        getContentPane().add(jCheckBox24);
        jCheckBox24.setBounds(200, 260, 75, 23);

        jCheckBox25.setText("Descamação");
        getContentPane().add(jCheckBox25);
        jCheckBox25.setBounds(200, 237, 85, 23);

        jCheckBox26.setText("Hematoma");
        getContentPane().add(jCheckBox26);
        jCheckBox26.setBounds(200, 191, 77, 23);

        jCheckBox27.setText("Vesicula");
        getContentPane().add(jCheckBox27);
        jCheckBox27.setBounds(200, 214, 63, 23);

        jCheckBox28.setText("Foliculite");
        getContentPane().add(jCheckBox28);
        jCheckBox28.setBounds(200, 329, 67, 23);

        jCheckBox29.setText("Xantelasma");
        getContentPane().add(jCheckBox29);
        jCheckBox29.setBounds(200, 283, 81, 23);

        jCheckBox30.setText("Angioma");
        getContentPane().add(jCheckBox30);
        jCheckBox30.setBounds(299, 145, 67, 23);

        jCheckBox31.setText("Ceratose");
        getContentPane().add(jCheckBox31);
        jCheckBox31.setBounds(299, 168, 69, 23);

        jCheckBox32.setText("Nodulos");
        getContentPane().add(jCheckBox32);
        jCheckBox32.setBounds(299, 191, 63, 23);

        jCheckBox33.setText("Crosta");
        getContentPane().add(jCheckBox33);
        jCheckBox33.setBounds(299, 214, 57, 23);

        jCheckBox34.setText("Escoriação");
        getContentPane().add(jCheckBox34);
        jCheckBox34.setBounds(299, 237, 77, 23);

        jCheckBox35.setText("Eczema");
        getContentPane().add(jCheckBox35);
        jCheckBox35.setBounds(299, 260, 61, 23);

        jCheckBox36.setText("Cicatriz");
        getContentPane().add(jCheckBox36);
        jCheckBox36.setBounds(299, 329, 61, 23);

        jCheckBox37.setText("Oleosidade");
        getContentPane().add(jCheckBox37);
        jCheckBox37.setBounds(299, 306, 79, 23);

        jCheckBox38.setText("Hipercromia");
        jCheckBox38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox38ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox38);
        jCheckBox38.setBounds(0, 352, 81, 23);

        jCheckBox39.setText("Eritema");
        getContentPane().add(jCheckBox39);
        jCheckBox39.setBounds(105, 352, 61, 23);

        jCheckBox40.setText("Populas");
        getContentPane().add(jCheckBox40);
        jCheckBox40.setBounds(200, 352, 63, 23);

        jCheckBox41.setText("Escara");
        getContentPane().add(jCheckBox41);
        jCheckBox41.setBounds(299, 352, 57, 23);

        jCheckBox42.setText("Fistula");
        jCheckBox42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox42ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox42);
        jCheckBox42.setBounds(0, 145, 57, 23);

        jCheckBox43.setText("Psoriase");
        getContentPane().add(jCheckBox43);
        jCheckBox43.setBounds(0, 375, 65, 23);

        jCheckBox44.setText("Espessura");
        getContentPane().add(jCheckBox44);
        jCheckBox44.setBounds(105, 375, 75, 23);

        jButton1.setText("Cadastrar");
        getContentPane().add(jButton1);
        jButton1.setBounds(214, 410, 81, 23);

        jButton2.setText("Cancelar");
        getContentPane().add(jButton2);
        jButton2.setBounds(305, 410, 75, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox38ActionPerformed

    private void jCheckBox42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox42ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox40;
    private javax.swing.JCheckBox jCheckBox41;
    private javax.swing.JCheckBox jCheckBox42;
    private javax.swing.JCheckBox jCheckBox43;
    private javax.swing.JCheckBox jCheckBox44;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
