/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author ki_ob
 */
public class jifBiometria extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifBiometria
     */
    public jifBiometria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Grau = new javax.swing.JComboBox<>();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        setTitle("Biometria");
        getContentPane().setLayout(null);

        jLabel2.setText("Braço Dir:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 20, 47, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(70, 20, 73, 20);

        jLabel3.setText("Braço Esq:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 50, 51, 14);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(70, 50, 73, 20);

        jLabel4.setText("Perna Dir:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 80, 48, 14);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(70, 80, 73, 20);

        jLabel5.setText("Perna Esq:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 110, 52, 14);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(70, 110, 73, 20);

        jLabel6.setText("Estomago:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 20, 51, 14);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(220, 20, 73, 20);

        jLabel7.setText("Cintura:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 50, 39, 14);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(220, 50, 75, 20);

        jLabel8.setText("Busto:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 80, 31, 14);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(220, 80, 73, 20);

        jLabel9.setText("Abdomen:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 110, 49, 14);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(220, 110, 71, 20);

        jLabel10.setText("Culote:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 20, 35, 14);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(360, 20, 73, 20);

        jLabel11.setText("Quadril:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(310, 50, 38, 14);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(360, 50, 73, 20);

        jLabel12.setText("Coxa Dir:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(310, 80, 45, 14);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(360, 80, 73, 20);

        jLabel13.setText("Coxa Esq:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(310, 110, 49, 14);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(360, 110, 73, 20);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 147, 440, 10);

        jRadioButton1.setText("Celulite:");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(10, 169, 65, 23);

        jRadioButton2.setText("Gordura Localizada:");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(10, 198, 121, 23);

        jRadioButton3.setText("Ptose:");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(10, 224, 57, 23);

        jRadioButton4.setText("Vibices:");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(10, 250, 61, 23);

        jLabel14.setText("Onde:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(149, 202, 30, 14);

        jLabel15.setText("Onde:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(149, 228, 30, 14);

        jLabel16.setText("Onde:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(149, 254, 30, 14);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(197, 199, 233, 20);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(197, 225, 233, 20);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(197, 251, 233, 20);

        jButton1.setText("Cadastrar");
        getContentPane().add(jButton1);
        jButton1.setBounds(204, 310, 81, 23);

        jButton2.setText("Cancelar");
        getContentPane().add(jButton2);
        jButton2.setBounds(303, 310, 75, 23);

        Grau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grau 1", "Grau 2", "Grau 3" }));
        Grau.setToolTipText("Grau");
        getContentPane().add(Grau);
        Grau.setBounds(120, 170, 70, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Grau;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    // End of variables declaration//GEN-END:variables
}
